# Generated by Django 2.2.4 on 2019-12-15 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=1000, null=True)),
                ('item1_img', models.CharField(max_length=1000, null=True)),
                ('item1_link', models.CharField(max_length=1000, null=True)),
                ('item2', models.CharField(max_length=1000, null=True)),
                ('item2_img', models.CharField(max_length=1000, null=True)),
                ('item2_link', models.CharField(max_length=1000, null=True)),
                ('item3', models.CharField(max_length=1000, null=True)),
                ('item3_img', models.CharField(max_length=1000, null=True)),
                ('item3_link', models.CharField(max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
